blueprints/open/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import login_user
from app import db
from models import User, Message, message_recv, Chat
from werkzeug.security import generate_password_hash, check_password_hash

bp_open = Blueprint('bp_open', __name__)


@bp_open.get('/')
def index():
    chat_data = db.session.query(Chat).all()
    messages_data = db.session.query(Message.has_been_read, message_recv).join(Message).all()
    return render_template("index.html", messages_data=messages_data, chat_data=chat_data)


@bp_open.get('/login')
def login_get():
    return render_template('login.html')


@bp_open.post('/login')
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    session['email'] = email
    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('bp_open.login_get'))  # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)

    login_user(user)
    user.online = True

    from app import db
    db.session.commit()

    return redirect(url_for('bp_user.profile_get'))


@bp_open.get('/signup')
def signup_get():
    return render_template('signup.html')


@bp_open.post('/signup')
def signup_post():
    name = request.form['name']
    email = request.form['email']
    password = request.form['password']
    hashed_password = generate_password_hash(password, method='sha256')

    user = User.query.filter_by(email=email).first()
    if user:
        flash("Email already in use.")
        return redirect(url_for('bp_open.signup_get'))

    new_user = User(name=name, email=email, password=hashed_password)

    from app import db
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('bp_open.login_get'))

blueprints/user/__init__.py
import re
from flask import Blueprint, render_template, session, request, redirect, url_for
from flask_login import current_user, login_required, logout_user
import mqtt_publish
from app import db
from controllers.message_controller import get_user_messages, create_message, mark_as_read, \
    create_chat, mark_as_notified
from controllers.user_controller import get_all_users, get_user_by_id, get_user_server_ip
from models import User, Message, message_recv, Chat

bp_user = Blueprint('bp_user', __name__)


@bp_user.post('/')
def mangocount_post():
    email = session['email']
    user = User.query.filter_by(email=email).first()
    if user.mangocount is None:
        user.mangocount = 1
    else:
        user.mangocount += 1
    db.session.commit()
    return render_template('index.html', mangocount=str(user.mangocount))


@bp_user.get('/profile')
def profile_get():
    users = get_all_users()
    chat_data = db.session.query(Chat).all()
    messages_data = db.session.query(Message.has_been_read, message_recv).join(Message).all()
    return render_template("profile.html", userlist=users, name=current_user.name, email=current_user.email,
                           mangocount=User.query.filter_by(email=current_user.email).first().mangocount,
                           messages_data=messages_data, chat_data=chat_data)


@bp_user.post('/profile')
def profile_post():
    email = session['email']
    user = User.query.filter_by(email=email).first()
    user.public_RSA = request.form['generated_RSA_public']
    public_key = re.sub("\n", "", user.public_RSA)
    db.session.commit()
    with open(f'./chat/rsa_keys/{current_user.name.lower()}_public.pem', 'w') as out_file:
        out_file.write(public_key)
    return redirect(url_for('bp_user.profile_get'))


@bp_user.get('/profile/<user_id>')
def profile_get_user(user_id):
    user_id = int(user_id)
    recipient = get_user_by_id(user_id)
    chat_data = db.session.query(Chat).all()
    name_client = get_user_by_id(user_id)
    ip_server = get_user_server_ip()
    messages_data = db.session.query(Message.has_been_read, message_recv).join(Message).all()
    return render_template('profile_user.html', recipient=recipient, messages_data=messages_data,
                           name_client=name_client,
                           ip_server=ip_server, chat_data=chat_data)


@bp_user.get('/inbox')
def inbox_get():
    messages = get_user_messages()
    chat_data = db.session.query(Chat).all()
    messages_data = db.session.query(Message.has_been_read, message_recv).join(Message).all()
    mark_as_read()
    return render_template("inbox.html", email=current_user.email, messages=messages, messages_data=messages_data,
                           chat_data=chat_data)


@bp_user.get('/chat_requests')
def chat_requests_get():
    chat_data = db.session.query(Chat).all()
    return render_template('chat_requests.html', chat_data=chat_data)


@bp_user.get('/chat_confirm')
def chat_confirm():
    mark_as_notified()
    return redirect(url_for('bp_open.index'))


@bp_user.post('/chat/<user_id>')
def chat_post(user_id):
    user_id = int(user_id)
    name_client = get_user_by_id(user_id)
    name_server = current_user.name
    ip_server = get_user_server_ip()
    create_chat(name_server, name_client.name, ip_server)
    return redirect(url_for('bp_open.index'))


@bp_user.get('/messages/<user_id>')
def messages_get_user(user_id):
    user_id = int(user_id)
    recipient = get_user_by_id(user_id)
    print(recipient)
    messages_data = db.session.query(Message.has_been_read, message_recv).join(Message).all()
    return render_template('messages.html', name=current_user.name, email=current_user.email, recipient=recipient,
                           messages_data=messages_data)


@bp_user.post('/messages/<user_id>')
def messages_post(user_id):
    title = request.form['title']
    content = request.form['content']
    encrypted_AES_key = request.form['encrypted_AES_key']
    user_id = int(user_id)
    create_message(title, content, user_id, encrypted_AES_key)
    mqtt_publish.publish(user_id, current_user.email)
    return redirect(url_for('bp_user.messages_get_sent'))


@bp_user.get('/messages/sent')
def messages_get_sent():
    chat_data = db.session.query(Chat).all()
    messages_data = db.session.query(Message.has_been_read, message_recv).join(Message).all()
    return render_template('message_sent.html', messages_data=messages_data, chat_data=chat_data)


@bp_user.get('/logout')
@login_required
def logout():
    user = current_user
    user.online = False
    from app import db
    db.session.commit()
    logout_user()
    return redirect(url_for('bp_open.index'))

controllers/message_controller.py
from flask_login import current_user
from app import db
from controllers.user_controller import get_user_by_id
from models import Message, message_recv, Chat


def create_message(title, content, recipient_id, encrypted_AES_key):
    from models import Message
    user = current_user
    message = Message(title=title, content=content, sender_id=user.id, has_been_read=False,
                      encrypted_AES_key=encrypted_AES_key)
    recipient_id = int(recipient_id)
    recipient = get_user_by_id(recipient_id)
    message.recipients.append(recipient)
    from app import db
    db.session.add(message)
    db.session.commit()


def create_chat(name_server, name_client, ip_server):
    from models import Chat
    chat = Chat(name_server=name_server, name_client=name_client, ip_server=ip_server)
    from app import db
    db.session.add(chat)
    db.session.commit()


def get_user_messages():
    return current_user.recv_messages


def mark_as_read():
    messages_data = db.session.query(Message.has_been_read, message_recv).join(Message).all()
    user_messages = []
    for message in messages_data:
        if current_user.id == message.user_id:
            user_messages.append(message.message_id)
    for message_id in user_messages:
        message = Message.query.filter_by(message_id=message_id).first()
        message.has_been_read = 1
        db.session.commit()


def mark_as_notified():
    chat_data = db.session.query(Chat).all()
    notifications = []
    for chat in chat_data:
        if current_user.name == chat.name_client:
            notifications.append(chat.id)
    for chat_id in notifications:
        chat = Chat.query.filter_by(id=chat_id).first()
        chat.notified = 1
        db.session.commit()

templates/base-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body>
<section class="hero is-primary">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        {% if current_user.admin %}
                            <a href="http://127.0.0.1:5000/admin" target="_blank" class="navbar-item">Admin</a>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            <a href="{{ url_for('bp_open.index') }}" class="navbar-item">Home</a>
                            <a href="{{ url_for('bp_user.inbox_get') }}" class="navbar-item">
                                <span class="icon-text">
                                    {% for message in messages_data %}
                                        {% if message.user_id == current_user.id %}
                                            {% if message.has_been_read == 0 %}
                                                <span class="icon is-small has-text-danger">
                                                    <i class="fas fa-circle icon"></i>
                                                </span>
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                    <span>Inbox</span>
                            </span>
                            </a>
                            <a href="{{ url_for('bp_user.profile_get') }}" class="navbar-item">Profile</a>
                            <a href="{{ url_for('bp_user.logout') }}" class="navbar-item">Logout</a>
                            <span class="navbar-item icon-text">
                                {% for chat in chat_data %}
                                    {% if chat.name_client == current_user.name %}
                                        {% if chat.notified == 0 %}
                                            <a href=" {{ url_for('bp_user.chat_requests_get') }}" style="color:#FF0000";>Chat Request</a>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </span>
                        {% endif %}
                        {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('bp_open.index') }}" class="navbar-item">Home</a>
                            <a href="{{ url_for('bp_open.login_get') }}" class="navbar-item">Login</a>
                            <a href="{{ url_for('bp_open.signup_get') }}" class="navbar-item">Sign Up</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>

</section>
{% block content %}
{% endblock %}

<div class="card-footer-item">
    <div class="hero-foot">
        <p>KYH2021 - Grupp 4. Copyright all rights reserved ©</p>
    </div>
</div>


</body>
</html>

templates/chat.html
{% extends "base-template.html" %}

{% block title %}
    Mango Chat
{% endblock %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <form action="{{ url_for('bp_user.chat_post',user_id = name_client.id) }}" method="POST" class="box">

            <input type="hidden" name="user_id" value="{{ name_client.id }}">
            <p>{{ current_user.name }}</p>
            <p>{{ name_client.name }}</p>
            <p>{{ ip_server }}</p>

            <button type="submit" class="button is-primary">Send chat request</button>
        </form>
    </div>

{% endblock %}

templates/chat_requests.html
{% extends "base-template.html" %}

{% block title %}
    Mango Chat
{% endblock %}

{% block content %}

    <div class="column is-4 is-offset-4">
        <p>Ready to connect!</p>
        <br>
        {% for chat in chat_data %}
            <tr>
                {% if chat.name_client == current_user.name %}
                    {% if not chat.notified %}
                        <script>
                            function confirmAction() {
                                let confirmAction = confirm("{{ chat.name_server }} wants to chat with you");
                                if (confirmAction) {
                                    alert("Copy string and start chat client: " +
                                        "{{ chat.ip_server }} {{ chat.name_server }} {{ chat.name_client }}");
                                } else {
                                    alert("Action canceled. No chat for you!");
                                }
                            }
                        </script>
                        {% if current_user.public_RSA == none %}
                            <p class="chat_text"
                               onclick="alert('No public RSA key found. Press ok for redirection'); window.location.href = '{{ url_for('bp_user.profile_get') }}'">{{ chat.name_server }}
                                wants to chat with you. Click text to confirm</p>
                        {% else %}
                            <p class="chat_text"
                               onclick="confirmAction(); window.location.href = '{{ url_for('bp_user.chat_confirm') }}'">{{ chat.name_server }}
                                wants to chat with you. Click text to confirm</p>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </tr>
        {% endfor %}
    </div>

{% endblock %}

templates/index.html
{% extends "base-template.html" %}

{% block title %}
    Mango Main
{% endblock %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h1 class="title">Welcome to the Mango Project!</h1>
        <p>The mango goes 'round, 'round and 'round 'round and 'round 'round and 'round!</p><br/>

        <div class="mango-wrapper">
            {% if current_user.is_authenticated %}
                <form action="{{ url_for('bp_user.mangocount_post') }}" method="POST">
                    <button class="hide-mango-button" type="submit">
                        <img class="list-thumbnail mango-spin" src="{{ url_for('static', filename='img/mango.gif') }}">
                    </button>
                </form>
                <form action="{{ url_for('bp_user.mangocount_post') }}" method="POST">
                    <button class="hide-mango-button" type="submit">
                        <img class="list-thumbnail mango-spin" src="{{ url_for('static', filename='img/mango.gif') }}">
                    </button>
                </form>
                <form action="{{ url_for('bp_user.mangocount_post') }}" method="POST">
                    <button class="hide-mango-button" type="submit">
                        <img class="list-thumbnail mango-spin" src="{{ url_for('static', filename='img/mango.gif') }}">
                    </button>
                </form>
            {% endif %}
            {% if not current_user.is_authenticated %}
                <img class="list-thumbnail mango-spin" src="{{ url_for('static', filename='img/mango.gif') }}">
                <img class="list-thumbnail mango-spin" src="{{ url_for('static', filename='img/mango.gif') }}">
                <img class="list-thumbnail mango-spin" src="{{ url_for('static', filename='img/mango.gif') }}">
            {% endif %}
        </div>
        <p>What a blessing! </p>
        {% if current_user.is_authenticated %}
            <p>Mango Count: {{ current_user.mangocount }} </p>
        {% endif %}
    </div>
    <script>
    window.setInterval('refresh()', 10000);
    function refresh() {
        window .location.reload();
    }
</script>
{% endblock %}

templates/login.html
{% extends "base-template.html" %}

{% block title %}
    Mango Login
{% endblock %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Mango - Login</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            <form action="{{ url_for('bp_open.login_post') }}" method="POST">

                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="password" name="password" placeholder="Your Password">
                    </div>
                </div>

                <div class="field">
                    <label class="checkbox">
                        <input type="checkbox">
                        Remember me
                    </label>
                </div>

                <button class="button is-block is-info is-large is-fullwidth">Login</button>


            </form>
        </div>
    </div>
{% endblock %}

templates/message_sent.html
{% extends "base-template.html" %}



{% block title %}
    Mango Messaging
{% endblock %}

{% block content %}

    <div class="column is-4 is-offset-4">
        <h1 class="title">Mango Messaging</h1>
        <p>Message sent!</p>
        <br/>
        <a href="{{ url_for('bp_user.profile_get') }}">
            <button type="button" class="button is-primary">Back</button>
        </a>
        <br/>
        <br/>
        <i>Signed in as {{ current_user.email }}</i>
        <br/>
        <br/>

    </div>
{% endblock %}

templates/messages.html
{% extends "base-template.html" %}



{% block title %}
    Mango Messaging
{% endblock %}

{% block content %}

    <div class="column is-4 is-offset-4">
        <h1 class="title">Mango Messaging</h1>
        <p>Message to: {{ recipient.email }}</p>
        <br/>
        <div class="field">
            <div class="box">
                <div class="control">
                    <label class="label">Autogenerated AES-key</label>
                    <input id="key" class="input text" placeholder="Autogenerated AES-Key"/>
                    <br/>
                    <br/>
                    <label class="label">Message</label>
                    <input id="plain" class="input text" placeholder="Message to Encrypt "/>
                    <br/>
                    <br/>
                    <button class="button is-primary" onclick="rsaEncrypt()">Encrypt & insert AES-key</button>
                    <button class="button is-primary" onclick="encrypt()">Encrypt message</button>
                    <i>Using {{ recipient.name }}s public RSA-key</i>
                </div>
            </div>
        </div>
        <br/>
        <br/>
        <form action="{{ url_for('bp_user.messages_post',user_id = recipient.id) }}" method="POST" class="box">
            <input type="hidden" name="user_id" value="{{ recipient.id }}">
            <input type="hidden" name="public_RSA" id="public_RSA" value="{{ recipient.public_RSA }}">
            <div class="field">
                <label class="label">Title</label>
                <div class="control">
                    <input name="title" class="input" type="text" placeholder="Message Title">
                </div>
            </div>
            <div class="field">
                <label class="label">Encrypted message</label>
                <div class="control">
                    <input id="cipher" name="content" class="input textarea" type="text" placeholder="">
                </div>
            </div>
            <div class="field">
                <label class="label">Encrypted AES-key</label>
                <div class="control">
                    <input id="encrypted_AES" name="encrypted_AES_key" class="input text" type="text" placeholder="">
                </div>
            </div>
            <button type="submit" class="button is-primary">Send</button>
        </form>
        <i>Signed in as {{ email }}</i>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
    <script src="../static/js/rsa.js"></script>
    <script>

        let key;
        let encrypted;
        let encrypted_rsa;
        let AES_key;
        let publicKey;

        function generateKey() {
            key = CryptoJS.lib.WordArray.random(16).toString();
            document.getElementById("key").value = key;
        }

        function encrypt() {
            let message = document.getElementById("plain").value;
            encrypted = CryptoJS.AES.encrypt(message, key);
            document.getElementById("cipher").value = encrypted;
        }

        function readPublicKey() {
            // Get the public file chooser files
            let files = document.getElementById("pub-file").files;
            // and exctract the first file, the one we want
            let file = files[0];

            // Create a file reader object
            let reader = new FileReader();

            // When the file is read, this function will be called
            reader.onloadend = function (event) {
                // Get the file contents
                publicKey = event.target.result;
                // Remove all new lines in the key
                publicKey = publicKey.replace(/(\r\n|\n|\r)/gm, "");
                // Notify the user that the file is read
                document.getElementById("pub-loaded").innerHTML = "Public key loaded";
            };

            // Read the file
            reader.readAsText(file);
        }

        function rsaEncrypt() {
            // Get the message to encrypt
            let AES_key = document.getElementById("key").value;
            // Create a RSA object
            let rsaEncrypt = new JSEncrypt();
            // Set the public key we want to use for encryption
            rsaEncrypt.setPublicKey(document.getElementById("public_RSA").value);
            // Show the encrypted message on the page
            document.getElementById("encrypted_AES").value = rsaEncrypt.encrypt(AES_key);
        }

        generateKey()


    </script>
{% endblock %}

templates/profile.html
{% extends "base-template.html" %}

{% block title %}
    Mango Profile
{% endblock %}

{% block content %}

    <div class="column is-4 is-offset-4">
        <h1 class="title">Users</h1>
        <table class="users">
            <tr>
                <th>User Name</th>
                <th>User email</th>
                <th>Online</th>
            </tr>
            {% for user in userlist %}
                <tr>
                    <td><a href="{{ url_for('bp_user.profile_get_user',user_id = user.id) }}">{{ user.name }}</a></td>
                    <td>{{ user.email }}</td>
                    <td class="center-content">
                        {% if user.online %}
                            <div class="circle online"></div>
                        {% else %}
                            <div class="circle offline"></div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <br/>
        <h1 class="title">Your Profile</h1>
        <p>Name: {{ current_user.name }}</p>
        <p>User id: {{ current_user.id }}</p>
        <p>Mango Count: {{ mangocount }}</p>
        <br/>
        <p>Generate your RSA-keys <a href="https://travistidwell.com/jsencrypt/demo/" target="_blank">HERE</a></p>
        <br/>
        <label class="label">Public RSA</label>
        {{ current_user.public_RSA }}
        <br/>
        <br/>
        <form action="{{ url_for('bp_user.profile_post') }}" method="POST" class="box">
            <label class="label">Submit new Public RSA-key</label>
            <div class="control">
                <textarea name="generated_RSA_public" rows="5" cols="55"></textarea>
            </div>
            <br/>
            <button type="submit" class="button is-primary">Send</button>
        </form>
        <br/>
        <i>Signed in as {{ current_user.email }}</i>
    </div>

{% endblock %}

templates/profile_user.html
{% extends "base-template.html" %}

{% block title %}
    Mango Profile - {{ recipient.name }}
{% endblock %}

{% block content %}


    <div class="column is-4 is-offset-4">
        <h1 class="title">User Profile for {{ recipient.name }}</h1>
        <p>Name: {{ recipient.name }}</p>
        <p>Username:<i> {{ recipient.email }}</i></p>
        <p>Mango Count: {{ recipient.mangocount }}</p>
        <br/>
        <label class="label">Public RSA</label>
        <p>{{ recipient.public_RSA }}</p>
        <br/>
        <br/>
        {% if recipient.public_RSA == none %}
            <i>{{ recipient.name }} needs to upload a Public RSA-key before we can send a message</i>
            <br/>
            <button class="button is-primary" type="button" disabled>Send message</button>
        {% else %}
            <button class="button is-primary" type="button" onclick="window.location.href='/messages/{{ recipient.id }}';">Send message</button>
            <br/>
            <br/>
        {% endif %}

        {% if recipient.online %}
            {% if current_user.public_RSA == none %}
                <form action="{{ url_for('bp_user.profile_get') }}">
                <button class="button is-primary" type="submit" onclick="alert('No public RSA key found. Press ok for redirection')">Send chat
                    request
                </button>
                </form>
            {% else %}
                <form action="{{ url_for('bp_user.chat_post',user_id = name_client.id) }}" method="POST">
                    <input type="hidden" name="user_id" value="{{ name_client.id }}">
                    <button class="button is-primary" type="submit"
                            onclick="alert('Chat request sent. Start chat server and type in both usernames')">Chat
                    </button>
                </form>
            {% endif %}
        {% else %}
            <button class="button is-primary" type="button" disabled>Chat</button>
        {% endif %}
    </div>
{% endblock %}

templates/signup.html
{% extends "base-template.html" %}

{% block title %}
    Mango Sign Up
{% endblock %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Mango - Sign Up</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('bp_open.login_get') }}">login page</a>
                    </div>
                {% endif %}
            {% endwith %}
            <form action="{{ url_for('bp_open.signup_post') }}" method="POST">
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="text" name="name" placeholder="Enter your full name"
                               autofocus=""/>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="email" name="email" placeholder="Your email address"
                               autofocus="">
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="password" name="password" placeholder="Enter password"
                               autofocus="">
                    </div>
                </div>
                <input type="submit" value="Sign up">
            </form>
        </div>
    </div>
{% endblock %}